
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-ebs
  namespace: app
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pg-app-claim
  namespace: app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-ebs
  resources:
    requests:
      storage: 10Gi