FROM golang:alpine3.15 as builder
WORKDIR /todo-app
COPY /go/go.mod .
# COPY /go/go.sum .
RUN go mod download
COPY /go server/
RUN cd server/cmd && go build -o todo-server server.go && chmod +x ./todo-server

FROM alpine
LABEL org.opencontainers.image.source https://github.com/benedicthomuth/bachelor-thesis
COPY --from=builder /todo-app/server/cmd/todo-server usr/bin/todo-server
CMD [ "todo-server" ]

